package com.wheelsup.util;

public class Simulation_Constants {

	public static final String RESPONSE =

			"{\"keys\":{\"google_places\":\"AIzaSyAuNQF6Dm6ESVt_dSc3xLHQHQNFemcOcfA\","
					+ "\"mapbox_flight_estimator_style\":\"mapbox://styles/haysom/cj7v13o5j2nqs2"
					+ "rn4zicugrql\",\"marketo_form_account\":\"541-LAT-007\",\"marketo_form_"
					+ "id\":\"3101\",\"google_plus\":\"https://plus.google.com/+WheelsUp8"
					+ "760\",\"google_tag_manager\":\"GTM-558MLHC\",\"twitter\":\"https://twitter."
					+ "com/WheelsUp\",\"footer_disclaimer\":\"Wheels Up does not operate aircraft;"
					+ " FAA licensed and DOT registered air carriers participating in the"
					+ " program exercise full operational control of all flights offered by or "
					+ "arranged through Wheels Up. For on-demand flights and shuttle flights "
					+ "operated as scheduled service, Wheels Up acts solely as an agent for "
					+ "Wheels Up members and guests in arranging these flights on their behalf. "
					+ "For shuttle flights operated as Public Charter service, Wheels Up acts"
					+ " as principal in offering these flights subject to the DOT’s Public Charter "
					+ "rules contained in 14 CFR Part 380. All aircraft owned or leased by Wheels "
					+ "Up are leased to the operating air carrier and are operated exclusively by"
					+ " that air carrier.\",\"instagram\":\"http://instagram.com/wheelsu"
					+ "p8760\",\"mapbox_accesstoken\":\"pk.eyJ1IjoiaGF5c29tIiwiYSI6ImNqMX"
					+ "phNzhiMTAxbGMyd3FsY2p6cTRkaDUifQ.i1LAjsh8bZTnx26Q6ltVhw\",\"mapbox_sty"
					+ "le\":\"mapbox://styles/haysom/cj9zzc58490o72supmyf1aowh\",\"email\":\"i"
					+ "nfo@wheelsup.com\",\"password\":\"\",\"facebook\":\"https://www.facebook"
					+ ".com/WheelsUp8760\"},\"footer\":[{\"title\":\"About Us\",\"subitem"
					+ "s\":[{\"title\":\"News\",\"url\":\"/news/\"},{\"title\":\"Our Stor"
					+ "y\",\"url\":\"/our-story/\"},{\"title\":\"Our Safety\",\"url\":\"/s"
					+ "afety/\"},{\"title\":\"Privacy Policy\",\"url\":\"/privacypolicy/\"}]"
					+ "},{\"title\":\"Ignore this! - test\",\"subitems\":[]},{\"title\":\"Learn"
					+ " More\",\"subitems\":[{\"title\":\"Member Events & Benefits\",\"url\""
					+ ":\"/events-experiences/\"},{\"title\":\"Wheels Up Cares\",\"url\":\"/w"
					+ "heelsupcares/\"},{\"title\":\"Careers\",\"url\":\"https://careers-whee"
					+ "lsup.icims.com/jobs/search\"},{\"title\":\"Request Info\",\"url\":\"/r"
					+ "equest-info/\"}]},{\"title\":\"Contact Us\",\"subitems\":[{\"title\":\"85"
					+ "5-FLY-8760\",\"url\":\"\"},{\"title\":\"info@wheelsup.com\",\"url\":\"mai"
					+ "lto:info@wheelsup.com\"}]}],\"redirects\":{\"fleet\":\"/fleet/king-ai"
					+ "r-350i/\",\"financial-analyst\":\"/our-story/\",\"vice-president-of-sale"
					+ "s-7\":\"/our-story/\",\"cnbc_12-23_1.html\":\"/\",\"key-areas-of-safety-"
					+ "assessment\":\"/safety/\",\"q-a\":\"/our-story/\",\"vice-president-of-s"
					+ "ales-6\":\"/our-story/\",\"company/testimonials?1926\":\"/our-st"
					+ "ory/\",\"company/testimonials?3796\":\"/our-story/\",\"range-and-trav"
					+ "el-time\":\"/individual-membership/\",\"vice-president-of-sales-8\":\"/our"
					+ "-story/\",\"member-services-representative\":\"/our-story/\",\"fleet/king"
					+ "-air-350ifdsfsdfdsf\":\"/fleet/king-air-350i/\",\"vice-president-of-sale"
					+ "s-5\":\"/our-story/\",\"advantages-over-traditional-charter-broke"
					+ "rs\":\"/individual-membership/\",\"form\":\"/request-info/\",\"quiet-"
					+ "cabin-noise-control\":\"/fleet/king-air-350i/\",\"nyt\":\"http://www."
					+ "wheelsup.com/request-info?utm_source=NYT&utm_medium=print&utm_campaign"
					+ "=NYT\",\"company/testimonials?1744\":\"/our-story/\",\"company/testimo"
					+ "nials\":\"/our-story/\",\"evp-member-experience-and-retention\":\"/our"
					+ "-story/\",\"business-analyst\":\"/our-story/\",\"wheels-down\":\"/our-s"
					+ "tory/\",\"digital-product-manager\":\"/our-story/\",\"fleet/helicopt"
					+ "er\":\"/fleet/king-air-350i/\",\"business-analyst-for-salesforce-c"
					+ "om\":\"/our-story/\",\"membership\":\"/individual-membership/\",\"comp"
					+ "any/our-story\":\"/our-story/\",\"fleet/flight-desk\":\"/fleet/king-"
					+ "air-350i/\",\"careers\":\"https://careers-wheelsup.icims.com/jobs/sea"
					+ "rch\",\"membership/corporate-membership\":\"/corporate-membership/\",\"wh"
					+ "y-the-king-air-350i\":\"/fleet/king-air-350i/\",\"company/testimonials?1"
					+ "823\":\"/our-story/\",\"benefits-coordinator\":\"/our-story/\",\"manage"
					+ "r-talent-acquisition\":\"/our-story/\",\"company/leadership\":\"/our-st"
					+ "ory/\",\"analyst-advanced-analytics\":\"/our-story/\",\"senior-devops-en"
					+ "gineer\":\"/our-story/\",\"company/wheelsup8760\":\"/our-story/\",\"vice"
					+ "-president-of-sales-3\":\"/our-story/\",\"membership/individual-and-fami"
					+ "ly\":\"/individual-membership/\",\"wsj\":\"http://www.wheelsup.com/reque"
					+ "st-info?utm_source=WSJ&utm_medium=print&utm_campaign=WSJ\",\"range-"
					+ "map\":\"/\",\"626\":\"/safety/\",\"why-the-citation-excelxls\":\"/fleet/cita"
					+ "tion-xls/\",\"fleet/the-wheels-up-citation-excelxls\":\"/fleet/citati"
					+ "on-xls/\",\"company/news\":\"/our-story/\",\"vice-president-of-sales-4\":\"/our"
					+ "-story/\",\"ux-ui-design-lead\":\"/our-story/\"},\"request-info\":{\"cta"
					+ "_url\":\"/request-info/\",\"cta_text\":\"Request info\"},\"header\":[{\"titl"
					+ "e\":\"Membership Options\",\"subitems\":[{\"title\":\"Connect Membershi"
					+ "p\",\"url\":\"/connect-membership/\"},{\"title\":\"Core Membership\",\"url\":\"/indiv"
					+ "idual-membership/\"},{\"title\":\"Business Membership\",\"url\":\"/corporate"
					+ "-membership/\"},{\"title\":\"Membership Comparison\",\"url\":\"/membershi"
					+ "p-comparison/\"}]},{\"title\":\"Members Only Fleet\",\"subitems\":[{\"ti"
					+ "tle\":\"King Air 350i\",\"url\":\"/fleet/king-air-350i/\"},{\"title\":\"Cit"
					+ "ation Excel/XLS\",\"url\":\"/fleet/citation-xls/\"}]},{\"title\":\"Charter "
					+ "Marketplace\",\"subitems\":[],\"url\":\"/charter-marketplace/\"}]}";

}
